-- =========================================================
-- DIGIFAB - SCHEMA BASE (MySQL 8)
-- =========================================================
CREATE DATABASE IF NOT EXISTS DIGIFAB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'digifab' IDENTIFIED BY 'digifab';
GRANT ALL PRIVILEGES ON DIGIFAB.* TO 'digifab';
FLUSH PRIVILEGES;

USE DIGIFAB;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- DROPS PARA RE-EXECUÇÃO SEGURA
DROP TABLE IF EXISTS CONSUMO_LOTE_MP;
DROP TABLE IF EXISTS MATERIA_PRIMA_ORDEM_PRODUCAO;
DROP TABLE IF EXISTS MATERIA_PRIMA_PRODUTO;
DROP TABLE IF EXISTS ORDEM_PRODUCAO;
DROP TABLE IF EXISTS LOTE_MP;
DROP TABLE IF EXISTS LOTE_PRODUTO;
DROP TABLE IF EXISTS LINHA_PRODUCAO;
DROP TABLE IF EXISTS MATERIA_PRIMA;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS USUARIO;

SET FOREIGN_KEY_CHECKS = 1;

-- =========================
-- TABELAS BASE
-- =========================

CREATE TABLE USUARIO (
  ID_USUARIO       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  EMAIL            VARCHAR(254) NOT NULL,
  NOME             VARCHAR(120) NOT NULL,
  SUB              VARCHAR(64),
  URL_FOTO         VARCHAR(500),
  CRIADO_EM        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
  CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UK_USUARIO_SUB   UNIQUE (SUB)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PRODUTO (
  ID_PRODUTO       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CODIGO           VARCHAR(50) NOT NULL,
  NOME             VARCHAR(150) NOT NULL,
  PESO_BRUTO       DECIMAL(10,3),
  UNIDADE_MEDIDA   VARCHAR(20) NOT NULL,
  CODIGO_BARRAS    VARCHAR(64),
  CRIADO_EM        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO),
  CONSTRAINT UK_PRODUTO_CODIGO   UNIQUE (CODIGO),
  CONSTRAINT UK_PRODUTO_CODBARRAS UNIQUE (CODIGO_BARRAS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FORNECEDOR (
  ID_FORNECEDOR    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CODIGO           VARCHAR(50) NOT NULL,
  NOME             VARCHAR(150) NOT NULL,
  CRIADO_EM        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_FORNECEDOR PRIMARY KEY (ID_FORNECEDOR),
  CONSTRAINT UK_FORNECEDOR_CODIGO UNIQUE (CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MATERIA_PRIMA (
  ID_MATERIA_PRIMA BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CODIGO           VARCHAR(50) NOT NULL,
  NOME             VARCHAR(140) NOT NULL,
  TEMP_MIN         DECIMAL(6,2),
  TEMP_MAX         DECIMAL(6,2),
  UNIDADE_MEDIDA   VARCHAR(20) NOT NULL,
  CRIADO_EM        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_MATERIA_PRIMA PRIMARY KEY (ID_MATERIA_PRIMA),
  CONSTRAINT UK_MATERIA_PRIMA_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_MP_TEMP CHECK (
    TEMP_MIN IS NULL OR TEMP_MAX IS NULL OR TEMP_MIN <= TEMP_MAX
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE LINHA_PRODUCAO (
  ID_LINHA_PRODUCAO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CODIGO            VARCHAR(50) NOT NULL,
  NOME              VARCHAR(120) NOT NULL,
  CAPACIDADE_HORA   INT UNSIGNED NOT NULL,
  DESCRICAO         VARCHAR(255),
  STATUS            ENUM('ATIVA','MANUTENCAO','INATIVA') NOT NULL DEFAULT 'ATIVA',
  ID_RESPONSAVEL    BIGINT UNSIGNED NULL,
  CRIADO_EM         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_LINHA_PRODUCAO PRIMARY KEY (ID_LINHA_PRODUCAO),
  CONSTRAINT UK_LINHA_PRODUCAO_CODIGO UNIQUE (CODIGO),
  INDEX IX_LINHA_PRODUCAO_ID_RESP (ID_RESPONSAVEL),
  CONSTRAINT FK_LINHA_PRODUCAO_USUARIO
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES USUARIO (ID_USUARIO)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- LOTES
-- =========================

CREATE TABLE LOTE_PRODUTO (
  ID_LOTE_PRODUTO  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CODIGO           VARCHAR(50) NOT NULL,
  ID_PRODUTO       BIGINT UNSIGNED NOT NULL,
  CIDADE_PRODUCAO  VARCHAR(120),
  CODIGO_FABRICA   VARCHAR(50),
  DATA_PRODUCAO    DATE,
  CRIADO_EM        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_LOTE_PRODUTO PRIMARY KEY (ID_LOTE_PRODUTO),
  CONSTRAINT UK_LOTE_PRODUTO_CODIGO UNIQUE (CODIGO),
  INDEX IX_LOTE_PRODUTO_ID_PRODUTO (ID_PRODUTO),
  INDEX IX_LOTE_PRODUTO_DATA (DATA_PRODUCAO),
  CONSTRAINT FK_LOTE_PRODUTO_PRODUTO
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE LOTE_MP (
  ID_LOTE_MP        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CODIGO            VARCHAR(50) NOT NULL,
  ID_MATERIA_PRIMA  BIGINT UNSIGNED NOT NULL,
  ID_FORNECEDOR     BIGINT UNSIGNED NOT NULL,
  NOTA_FISCAL       VARCHAR(50),
  DATA_RECEBIMENTO  DATE,
  QUANTIDADE        DECIMAL(12,3) UNSIGNED NOT NULL,
  DATA_VALIDADE     DATE,
  ID_RESPONSAVEL    BIGINT UNSIGNED NOT NULL,
  CRIADO_EM         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_LOTE_MP PRIMARY KEY (ID_LOTE_MP),
  CONSTRAINT UK_LOTE_MP_CODIGO UNIQUE (CODIGO),
  INDEX IX_LOTE_MP_ID_MP   (ID_MATERIA_PRIMA),
  INDEX IX_LOTE_MP_ID_FORN (ID_FORNECEDOR),
  INDEX IX_LOTE_MP_ID_RESP (ID_RESPONSAVEL),
  CONSTRAINT FK_LOTE_MP_MATERIA_PRIMA
    FOREIGN KEY (ID_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_LOTE_MP_FORNECEDOR
    FOREIGN KEY (ID_FORNECEDOR)  REFERENCES FORNECEDOR (ID_FORNECEDOR)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_LOTE_MP_USUARIO
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES USUARIO (ID_USUARIO)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT CK_LOTE_MP_DATAS CHECK (
    DATA_VALIDADE IS NULL OR DATA_RECEBIMENTO IS NULL OR DATA_VALIDADE >= DATA_RECEBIMENTO
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- ORDEM DE PRODUÇÃO
-- =========================

CREATE TABLE ORDEM_PRODUCAO (
  ID_ORDEM_PRODUCAO   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  CODIGO              VARCHAR(50) NOT NULL,
  ID_LOTE_PRODUTO     BIGINT UNSIGNED NOT NULL,
  ID_LINHA_PRODUCAO   BIGINT UNSIGNED NOT NULL,
  ID_RESPONSAVEL      BIGINT UNSIGNED NOT NULL,
  QUANTIDADE_PRODUZIR INT UNSIGNED NOT NULL,
  DT_HORA_INICIO      DATETIME NOT NULL,
  CRIADO_EM           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_ORDEM_PRODUCAO PRIMARY KEY (ID_ORDEM_PRODUCAO),
  CONSTRAINT UK_ORDEM_PRODUCAO_CODIGO UNIQUE (CODIGO),
  INDEX IX_OP_ID_LOTE_PRODUTO (ID_LOTE_PRODUTO),
  INDEX IX_OP_ID_LINHA_PROD   (ID_LINHA_PRODUCAO),
  INDEX IX_OP_ID_RESP         (ID_RESPONSAVEL),
  INDEX IX_OP_DT_INICIO       (DT_HORA_INICIO),
  CONSTRAINT FK_OP_LOTE_PRODUTO
    FOREIGN KEY (ID_LOTE_PRODUTO)   REFERENCES LOTE_PRODUTO   (ID_LOTE_PRODUTO)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_OP_LINHA_PRODUCAO
    FOREIGN KEY (ID_LINHA_PRODUCAO) REFERENCES LINHA_PRODUCAO (ID_LINHA_PRODUCAO)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_OP_USUARIO
    FOREIGN KEY (ID_RESPONSAVEL)    REFERENCES USUARIO        (ID_USUARIO)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- RELAÇÕES (BOM e PLANEJAMENTO)
-- =========================

CREATE TABLE MATERIA_PRIMA_PRODUTO (
  ID_MATERIA_PRIMA_PRODUTO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_PRODUTO               BIGINT UNSIGNED NOT NULL,
  ID_MATERIA_PRIMA         BIGINT UNSIGNED NOT NULL,
  QUANTIDADE_UNIDADE       DECIMAL(12,3) UNSIGNED NOT NULL,
  CRIADO_EM                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_MP_PRODUTO PRIMARY KEY (ID_MATERIA_PRIMA_PRODUTO),
  CONSTRAINT UK_MP_PRODUTO_UNICO UNIQUE (ID_PRODUTO, ID_MATERIA_PRIMA),
  INDEX IX_MP_PRODUTO_ID_PROD (ID_PRODUTO),
  INDEX IX_MP_PRODUTO_ID_MP   (ID_MATERIA_PRIMA),
  CONSTRAINT FK_MP_PRODUTO_PRODUTO
    FOREIGN KEY (ID_PRODUTO)       REFERENCES PRODUTO       (ID_PRODUTO)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_MP_PRODUTO_MP
    FOREIGN KEY (ID_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MATERIA_PRIMA_ORDEM_PRODUCAO (
  ID_MATERIA_PRIMA_ORDEM_PRODUCAO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_ORDEM_PRODUCAO               BIGINT UNSIGNED NOT NULL,
  ID_MATERIA_PRIMA                BIGINT UNSIGNED NOT NULL,
  QUANTIDADE_PREVISTA             DECIMAL(12,3) UNSIGNED NOT NULL,
  CRIADO_EM                       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM                   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_MP_ORDEM_PROD PRIMARY KEY (ID_MATERIA_PRIMA_ORDEM_PRODUCAO),
  CONSTRAINT UK_MP_ORDEM_PROD_UNICO UNIQUE (ID_ORDEM_PRODUCAO, ID_MATERIA_PRIMA),
  INDEX IX_MP_OP_ID_OP (ID_ORDEM_PRODUCAO),
  INDEX IX_MP_OP_ID_MP (ID_MATERIA_PRIMA),
  CONSTRAINT FK_MP_OP_ORDEM_PROD
    FOREIGN KEY (ID_ORDEM_PRODUCAO) REFERENCES ORDEM_PRODUCAO (ID_ORDEM_PRODUCAO)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_MP_OP_MP
    FOREIGN KEY (ID_MATERIA_PRIMA)  REFERENCES MATERIA_PRIMA  (ID_MATERIA_PRIMA)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- OPCIONAL: CONSUMO REAL POR LOTE DE MP
-- =========================

CREATE TABLE CONSUMO_LOTE_MP (
  ID_CONSUMO_LOTE_MP   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_ORDEM_PRODUCAO    BIGINT UNSIGNED NOT NULL,
  ID_LOTE_MP           BIGINT UNSIGNED NOT NULL,
  QUANTIDADE_CONSUMIDA DECIMAL(12,3) UNSIGNED NOT NULL,
  DATA_CONSUMO         DATETIME NOT NULL,
  CRIADO_EM            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATUALIZADO_EM        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_CONSUMO_LOTE_MP PRIMARY KEY (ID_CONSUMO_LOTE_MP),
  INDEX IX_CONSUMO_ID_OP      (ID_ORDEM_PRODUCAO),
  INDEX IX_CONSUMO_ID_LOTE_MP (ID_LOTE_MP),
  CONSTRAINT FK_CONSUMO_OP
    FOREIGN KEY (ID_ORDEM_PRODUCAO) REFERENCES ORDEM_PRODUCAO (ID_ORDEM_PRODUCAO)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_CONSUMO_LOTE_MP
    FOREIGN KEY (ID_LOTE_MP)        REFERENCES LOTE_MP        (ID_LOTE_MP)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Garantir FK novamente (se rodou trechos separados)
SET FOREIGN_KEY_CHECKS = 1;